version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    target-branch: master
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    target-branch: master
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
